.job_template: &build_script_definition
  tags:
    # Make you job be executed in a shared runner that has CVMFS mounted
    - cvmfs
  stage: build
  image: gitlab-registry.cern.ch/ci-tools/ci-worker:cc7
  script:
    # access sft.cern.ch
    - ls /cvmfs/sft.cern.ch/

    - export GCC_BASE="/cvmfs/sft.cern.ch/lcg/contrib/gcc/${GCC_VERSION_SHORT}/${GCC_VERSION_LONG}"
    - export ROOT_BASE="/cvmfs/sft.cern.ch/lcg/app/releases/ROOT/${ROOT_VERSION}/${GCC_VERSION_LONG}"
    # GitLab-CI sets the errexit option (set -e) so the build stops when a
    # command fails, but environment setup scripts typically expect errexit off.
    # Temporarily disable errexit when sourcing the setup script.
    - set +e && source ${ROOT_BASE}/bin/thisroot.sh; set -e
    - set +e && source ${GCC_BASE}/setup.sh; set -e
    - export CC=$(which gcc)
    - export CXX=$(which g++)
    - mkdir build && mkdir install && cd ./build
    - /cvmfs/sft.cern.ch/lcg/contrib/CMake/3.13.4/Linux-x86_64/bin/cmake -DCMAKE_INSTALL_PREFIX=../install ..
    - make && make install

stages:
  - build
  - test

# 6.14.06/x86_64-centos7-gcc48-opt
6_14_06__x86_64-centos7-gcc48-opt:
  variables:
    ROOT_VERSION: "6.14.06"
    GCC_VERSION_SHORT: "4.8"
    GCC_VERSION_LONG: "x86_64-centos7-gcc48-opt"
  <<: *build_script_definition



